
language: node_js

sudo: false

node_js:
  - 8

install: true

script:
  - pwd

before_install:
  - pip install --user awscli
  - aws configure set default.region us-east-1

after_success:
  - pwd
  - ls -al
  - mkdir codedeployLambda_artifact
  - zip -r csye6225-lambda.zip webapp/index.js
  - ls -al
  - mv csye6225-lambda.zip codedeployLambda_artifact/
  - ls -al
  - pwd
  - cd codedeployLambda_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:
  - provider: s3
    local_dir: codedeployLambda_artifact
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
      branch: master
after_deploy:
   - aws lambda update-function-code --zip-file=fileb://codedeployLambda_artifact/csye6225-lambda.zip --region=us-east-1 --function-name=PasswordResetLambda --publish
