
language: java
jdk:
  - oraclejdk8

sudo: false

install: true

script:
  - pwd

after_success:
  - pwd
  - ls -al
  - mkdir codedeploy_artifact
  - cp infrastructure/aws/codedeploy/*.sh .
  - cp infrastructure/aws/codedeploy/*.yml .
  - zip -r csye6225-lambda.zip webapp/cloud-application-lambda/target/cloud-application-lambda.jar *.sh *.yml
  - ls -al
  - mv csye6225-lambda.zip codedeploy_artifact/
  - ls -al
  - pwd
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:
  - provider: s3
    local_dir: codedeploy_artifact
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
      branch: master
  - provider: lambda
    function_name: "lambda-test"
    region: "us-east-1"
    runtime: "java8"
    # role: $role
    handler_name: "com.neu.lambda.Handler"
    on:
      branch: master
